### ISSUE TITLE
Update to 4.1.8.1833 Dreame Bot L10 Pro? Mihome.

### ISSUE THREAD

**Issue by stylishkrio** [pooyashahidi/xiaomi_vacuum#19]
Cleaning mode, cleaning time, room name. Will there be integration improvements?
![Screenshot_20220419-135152~2.png](https://user-images.githubusercontent.com/77132140/163988505-3bb7e6ac-7cfb-4534-941f-cf88abe914db.png)
![Screenshot_20220419-171321~2.png](https://user-images.githubusercontent.com/77132140/164024260-830bb7ff-ced5-4ea6-a200-a6eea914997a.png)

**Comment by pooyashahidi** [comment]
Room name will not happen as the python miio only uses indices.
I still have not received my vacuum bot though because of lockdown in china. I will resume development shortly after I get it. But as different devices have different features I cannot implement them all without the actual device to test. I only had a D9 and that one did not have some of the features like mop only. Cleaning time was however displayed correctly.
