### ISSUE TITLE
Lovelace vacuum card configuration

### ISSUE THREAD

**Issue by RoboMagus** [pooyashahidi/xiaomi_vacuum#6]
I'm interested in knowing how you managed to get the mop water flow to be shown in the [vacuum card example](https://github.com/pooyashahidi/xiaomi_vacuum#lovelace-card).

Could you share your config for this card please?

I'm using this plugin and the card with a Dreame L10 Pro, which also has a mopping feature with water control but I can't get it to show the waterflow next to the suction strength..

**Comment by pooyashahidi** [comment]
I modified the code myself. But since then I changed my whole lovelace ui and don't use that card anymore.
you can start here if you want to do the same: [how-to-run-locally ](https://github.com/denysdovhan/vacuum-card/blob/master/CONTRIBUTING.md#how-to-run-locally)  
Use the fan speed code as an example and and do the same with `water_level` and `water_level_list`
