### ISSUE TITLE
Lovelace cards code and help with entities

### ISSUE THREAD

**Issue by GizmoLibre** [pooyashahidi/xiaomi_vacuum#8]
Hey pooyashahidi. As i don't wanna add more offtopic to the "Add support for Dreame D9 Robot Vacuum (dreame.vacuum.p2009) #870", i will ask a couple of questions here. First of all, thanks for the lovelace code you provided there, it indeed has been helpful in recreating your cards. I am not that much interested in copying exact theme and style of them (that is why i did not apply the theme from matt8707), it is the functionality of the cards that i seek. As you can tell, i am a beginner, so a lot of stuff here is kinda difficult for me to figure out alone. Not just me, i hope this will be useful to all other newbies that wonder how did you do this or that :)

So, my inquires are - can you provide more info on how can i make those binary sensor entitites, such as binary_sensor.d9_active, binary_sensor.d9_active_not_paused, or entities such as input_select.d9_fan_speed and input_select.d9_water_level. I know that you make them from template section in configuration.yaml but other than that i have no clue what to add there. Also, i require your popup_vacuum_rooms.yaml since i have no idea how to structure any of this. 

Custom Icons too if you are willing to share, as i am missing custom:main_brush, custom:side_brush, and custom:valetudo ones. You don't have to go in detail with writing, you can provide the files i mentioned with a short commentary about them, and i will modify them to my case, since i do have the basic knowledge of applying the code. I am just lost with creating those new entities needed to make the cards work, believe me, i tried, got so lost and failed :D Thanks man, great work in general. Cheers.

![d9ha2](https://user-images.githubusercontent.com/46543823/133943958-6b87cc87-6741-4cb0-ba40-3ef7c00d3d38.jpg)

**Comment by pooyashahidi** [comment]
Hey, no problem. I made those template sensors to change the UI according the status. I am not that experienced with Homeassistant myself. that is why I'm usually not that keen on sharing my config and stuff. there are probably better ways to do that but this is what I did.
here is the templates you mentioned:

```yaml
template:
  binary_sensor:
    - name: D9 Active
      state: >
          {{
            is_state("vacuum.dreame_d9", "cleaning")
            or
            is_state("vacuum.dreame_d9", "mopping")
            or
            is_state("vacuum.dreame_d9", "paused")
            or
            is_state("vacuum.dreame_d9", "returning")
          }}
    - name: D9 Active Not Paused
      state: >
        {{
          is_state("vacuum.dreame_d9", "cleaning")
          or
          is_state("vacuum.dreame_d9", "mopping")
          or
          is_state("vacuum.dreame_d9", "returning")
        }}
```

In order to get the inputs easiest way is to use helpers (config>helpers) and use the UI to create them. 
or in yaml like this:

```yaml
input_number:
  repeats:
    name: Repeats
    initial: 4
    min: 1
    max: 10
    step: 1
    mode: slider

input_select:
  d9_fan_speed:
    name: Fan Speed
    icon: mdi:fan
    options:
      - Quiet
      - Standard
      - Strong
      - Turbo
  d9_water_level:
    name: Water Level
    icon: mdi:water
    options:
      - Low
      - Medium
      - High
```

About the custom icons I wrote a small JS script that returns svgs. There was a file loader but the repo is deleted now. [This thread](https://community.home-assistant.io/t/custom-icons-loader/164325/17) should have all the info you need.

the custom cleanup popup is probably my most cluttered ever but you can find it [here](https://gist.github.com/pooyashahidi/d5d364d809aa7f76f69ae4558b840e66)

I will also add the vacuum popoup here from the other thread to prevent further discussions there.
[...] here is the [extremely ugly code](https://gist.github.com/pooyashahidi/b3a7e1859d9f6d5751047b391fce09ec) for the popup.

**Comment by jackdalma** [comment]
Hello @pooyashahidi, thank you for your work.
I really like your lovelace ui for the vacuum and I'm trying to replicate it, but I have a question about your [extremely ugly code](https://gist.github.com/pooyashahidi/b3a7e1859d9f6d5751047b391fce09ec) ;)
I'm not experienced with homeassistant either, but I can't get the javascript template to work to display the remaining time in the bar-card name. For what i could understand, bar-card does not accept template. am I missing something?

Thank you.

**Comment by pooyashahidi** [comment]
hi, thanks for the kind words. To be honest I don't think I did anything special for it to work. At least I don't remember if I did!
if you want more freedom with templating maybe [config-template-card](https://github.com/iantrich/config-template-card) helps
